### ISSUE TITLE
Checksum for UTF8 

### ISSUE THREAD

**Issue by registerboy** [NiceAndNerdy/SIP2.NET#2]
When input a UTF-8 non English string will get a wrong check sum. Please help.... thanks

**Comment by NiceAndNerdy** [comment]
I'm afraid it's only setup to handle English strings.  The code file that handles the checksum is https://github.com/NiceAndNerdy/SIP2.NET/blob/master/SIP2_NET/CheckSum.cs .  You would have to modify that for it to work with different character encoding.

**Comment by registerboy** [comment]
revise the below code for UTF-8 ?
  for (intCtr = 0; intCtr <= chrArray.Length - 1; intCtr++)
            {
                intAscSum = intAscSum + (chrArray[intCtr]);
            }

**Comment by registerboy** [comment]
the issues is solved by Replace 

for (intCtr = 0; intCtr <= chrArray.Length - 1; intCtr++)
{
intAscSum = intAscSum + (chrArray[intCtr]);
}

with
            byte[] bytes = Encoding.UTF8.GetBytes(strMsg);
            int i = 0;
            for (i = 0; i < bytes.Length; i++)
            {
                intAscSum = intAscSum + bytes[i];
            }
NiceAndNerdy, you can remark it in the source code. I have test it working on 3M selfcheck system and Sirsi Dynix Symphony. Thanks.

**Comment by NiceAndNerdy** [comment]
Just saw this!  I'll be sure to add this to the source.  Thank you so much!

Mark
