### ISSUE TITLE
Sequence Number ASCII digit. '0' to '9'

### ISSUE THREAD

**Issue by MerlinsSword** [NiceAndNerdy/SIP2.NET#4]
in SipFactoryWithCheckSum the incrementer (Sequence Number) is not limited to 9

I was testing the Library on the SirsiDynix Library system and could only do a limited number of command before the server responded with 96 (resend).

3M SIP2 protocol PDF -> The sequence number is a single ASCII digit. '0' to '9'

Suggested fix:
            incrementer++;
            if (incrementer == 10)
            {
                incrementer = 0;
            }

**Comment by NiceAndNerdy** [comment]
Fixed!  Thank you for pointing that out!
